version: "3.8"

services:
  database:
    image: postgres:15-alpine # The specific box we want (Alpine is a super lightweight version)
    environment:
      POSTGRES_USER: simo
      POSTGRES_PASSWORD: elyou
      POSTGRES_DB: alloy
    ports:
      - "5432:5432" # Maps [Ubuntu Port] : [Container Port]
